#!/bin/bash
##########此处的IP地址，反向解析的IP，域名 可修改#############
IP="192.168.20.129"
RIP="20.168.192"
DN="hihihi.com"
Name="192.168.20"
######################备份##################################
cp -p /etc/named.rfc1912.zones /etc/named.rfc1912.zones.bak
cp -p /etc/named.conf /etc/named.conf.bak  
############################################################ 
sed -i 's/127.0.0.1/any/g' /etc/named.conf
sed -i 's/localhost/any/g' /etc/named.conf
############################################################
cat >> /etc/named.rfc1912.zones << +END+
zone "$DN" IN {
         type master;
         file "$DN.zone";
	 allow-update { none; };
};
zone "$RIP.in-addr.arpa" IN{
        type master;
        file "$Name.zone";
	allow-update { none; };
};
+END+

############################################################
touch /var/named/$DN.zone
cat > /var/named/$DN.zone <<+END+
\$TTL 86400
@ 	IN 	SOA 	dns.$DN. 	root.$DN. (
			2011091200 ; serial
			3H ; refresh
			1H ; retry
			1W ; expire
			0) ; minimum

@ 	IN 	NS	dns.$DN.
dns 	IN 	A 	$Name.129
www 	IN 	A 	$Name.129
ftp 	IN 	A 	$Name.129
pop3 	IN 	A 	$Name.129
smtp 	IN 	A 	$Name.129
+END+
############################################################
touch /var/named/$Name.zone
cat > /var/named/$Name.zone <<+END+
\$TTL 86400
@       IN      SOA     dns.$DN.       root.$DN. (
                        2011091200 ; serial
                        3H ; refresh
                        1H ; retry
                        1W ; expire
                        0) ; minimum
@   	 IN 	 NS	 dns.$DN.
129      IN      PTR     dns.$DN.
129      IN      PTR     www.$DN.
129      IN      PTR     mail.$DN.
+END+
############################################################
cp -a -f /etc/named* /var/named/chroot/etc/
cp -a -f /var/named/named* /var/named/chroot/var/named/
cp -a -f /var/named/$Name* /var/named/chroot/var/named/
cp -a -f /var/named/$DN* /var/named/chroot/var/named/

cat > /etc/resolv.conf <<+END+
#nameserver $IP
# Generated by NetworkManager
search localdomain
nameserver $IP
nameserver 192.168.20.2
+END+
############################################################
service iptables stop
service named start
serivce iptables start
nslookup www.$DN
nslookup $IP 
